export const localization = {
  En: {
    appName: "TaskTogether",
    slogan: "Collaborative Family Workspace",
    signInG: "Sign in with Google",
    welcomeTitle: "Organize Family Work",
    welcomeDesc: "Sync tasks, manage household milestones, and communicate in a live group chat. Built for family harmony.",
    createWorkspace: "Create Family Workspace",
    joinWorkspace: "Join with Invite Code",
    workspaceName: "Household Name",
    workspaceNamePlaceholder: "e.g., Karamana House, Green Family",
    inviteCode: "Invite Code",
    inviteCodePlaceholder: "e.g., FAM-2026",
    createBtn: "Create Group",
    joinBtn: "Join Group",
    workspaceTitle: "Set Up Family",
    tasksTab: "Tasks",
    chatTab: "Family Chat",
    profileTab: "Profile",
    allTasks: "All",
    myTasks: "My Duties",
    highPriority: "High Priority",
    addTask: "New Work Goal",
    title: "Title",
    description: "Description",
    priority: "Priority",
    assignee: "Assign To",
    submit: "Add Goal",
    cancel: "Cancel",
    low: "Low",
    medium: "Medium",
    high: "High",
    noTasks: "No active family tasks. Tap plus button to create!",
    chatPlaceholder: "Type to household...",
    googleSignInSuccess: "Successfully authorized Google identity",
    workspaceCreated: "Workspace created successfully",
    membersTitle: "Workspace Family Members",
    owner: "Group Owner",
    admin: "Admin",
    member: "Member",
    logout: "Sign Out",
    welcomeUser: "Welcome, ",
    inviteCodeLabel: "Group Invite Code: ",
    copiedCode: "Code Copied!",
    inviteSub: "Share this code with your spouse, children, or household to collaborate in real-time.",
    languageLabel: "Application Interface Language:",
    themeLabel: "Visual theme display settings:",
    lightMode: "Bright (Light)",
    darkMode: "Minimal (Dark)",
    simulateTaskCreated: "Auto Task Scheduled!",
  },
  Fa: {
    appName: "تسک‌توگدر",
    slogan: "فضای کاری مشترک خانواده",
    signInG: "ورود آسان با حساب گوگل",
    welcomeTitle: "سازمان‌دهی امور خانواده",
    welcomeDesc: "وظایف را همگام‌سازی کنید، نقاط عطف خانه را مدیریت کنید و در یک گفتگوی زنده با هم هماهنگ شوید.",
    createWorkspace: "ساخت فضای کاری جدید",
    joinWorkspace: "ورود با کد دعوت خانوادگی",
    workspaceName: "نام کلبه / خانواده",
    workspaceNamePlaceholder: "مانند: خانواده کارامانا، خانه امید",
    inviteCode: "کد دعوت",
    inviteCodePlaceholder: "نمونه: FAM-2026",
    createBtn: "ساخت خانه جدید",
    joinBtn: "پیوستن به خانه",
    workspaceTitle: "راه‌اندازی خانه مشترک",
    tasksTab: "کارها",
    chatTab: "چت خانوادگی",
    profileTab: "پروفایل",
    allTasks: "همه کارها",
    myTasks: "کارهای من",
    highPriority: "اولویت بالا",
    addTask: "افزودن کار جدید",
    title: "عنوان کار",
    description: "توضیحات بیشتر",
    priority: "میزان اولویت",
    assignee: "مسئول انجام",
    submit: "ثبت کار",
    cancel: "انصراف",
    low: "کم",
    medium: "متوسط",
    high: "زیاد",
    noTasks: "هیچ کاری ثبت نشده است. روی + کلیک کنید!",
    chatPlaceholder: "پیامی به خانواده بفرستید...",
    googleSignInSuccess: "احراز هویت گوگل با موفقیت انجام شد",
    workspaceCreated: "خانه خانوادگی با موفقیت ساخته شد",
    membersTitle: "اعضای کلبه مشترک",
    owner: "بنیان‌گذار خانه",
    admin: "مدیر",
    member: "عضو خانواده",
    logout: "خروج از حساب",
    welcomeUser: "خوش آمدید، ",
    inviteCodeLabel: "کد دعوت خانواده: ",
    copiedCode: "کد کپی شد!",
    inviteSub: "این کد را با همسر، فرزندان یا هم‌اتاقی‌های خود به اشتراک بگذارید تا همزمان همکاری کنید.",
    languageLabel: "زبان رابط کاربری برنامه:",
    themeLabel: "تنظیمات پوسته ظاهری:",
    lightMode: "روشن (روز)",
    darkMode: "تاریک (شب)",
    simulateTaskCreated: "وظیفه خودکار ایجاد شد!",
  }
};
